
services:
    image-service:
        build:
            context: .
            dockerfile: deployment/docker/Dockerfile
        ports:
        - "8000:8000"
        environment:
            - AWS_REGION=ap-south-1
            - S3_BUCKET_NAME=image-service-bucket-ap-south-1
            - DYNAMODB_TABLE_NAME=image-service-table-ap-south-1

